#ifndef GLOBALS_H
#define GLOBALS_H

#define BPM 128
#define MPW 6
#define BPW 24
#define EPW 48
#define NSPB (60000000000/BPM)
#define NSPE (NSPB/2)
#define NSPS (NSPE/2)
#define TIMER_DELAY 0
#define FUNCTION_DELAY 0

#define SMP_MEASURE_COUNT 336
#define WAVE_MEASURE_COUNT 48
#define SONG_SIXTEENTH_COUNT 3603

#define WAVE_COUNT (WAVE_MEASURE_COUNT/MPW)
#define NTE_WIDTH 48
#define NTE_HEIGHT 12
#define NTE_AREA (NTE_WIDTH*NTE_HEIGHT)
#define SMP_WIDTH 24
#define SMP_HEIGHT NTE_HEIGHT
#define SMP_AREA (SMP_WIDTH*SMP_HEIGHT)
#define LYRIC_WIDTH (NTE_WIDTH+SMP_WIDTH)
#define LYRIC_HEIGHT 8
#define LYRIC_AREA (LYRIC_WIDTH*LYRIC_HEIGHT)
#define WINDOW_WIDTH LYRIC_WIDTH
#define WINDOW_HEIGHT (LYRIC_HEIGHT+NTE_HEIGHT)
#define WINDOW_AREA (WINDOW_WIDTH*WINDOW_HEIGHT)

/* Layout 1
#define NTE_WIDTH 72
#define NTE_HEIGHT 6
#define NTE_AREA NTE_WIDTH*NTE_HEIGHT
#define LYRIC_WIDTH NTE_WIDTH
#define LYRIC_HEIGHT 6
#define LYRIC_AREA LYRIC_WIDTH*LYRIC_HEIGHT
#define SMP_WIDTH 21
#define SMP_HEIGHT LYRIC_HEIGHT+NTE_HEIGHT
#define SMP_AREA SMP_WIDTH*SMP_HEIGHT
#define WINDOW_WIDTH LYRIC_WIDTH+SMP_WIDTH
#define WINDOW_HEIGHT SMP_HEIGHT
#define WINDOW_AREA WINDOW_WIDTH*WINDOW_HEIGHT
*/

extern int LOGO_WIDTH;
extern int LOGO_HEIGHT;
extern int LOGO_X0;
extern int LOGO_Y0;
extern int SMP_Y0;

#endif